name: Metrics
on:
  # Schedule updates (each day)
  schedule: [{cron: "0 0 * * *"}]
  # Run workflow manually
  workflow_dispatch:
  # Run workflow when pushing on main
  push: {branches: ["main"]}
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: General
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_order: base.header, base.activity+community, base.repositories, isocalendar, languages
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_indepth: yes
          plugin_languages_limit: 4
          plugin_languages_sections: most-used, recently-used
