name: Metrics
on:
  # Schedule updates (each day)
  schedule: [{ cron: "0 0 * * *" }]
  # Run workflow manually
  workflow_dispatch:
  # Run workflow when pushing on main
  push: { branches: ["main"] }
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Metrics - Left
        uses: ahdinosaur/metrics@handle-more-repos
        with:
          filename: metrics.left.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_order: base.header, base.activity+community, base.repositories
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          repositories: 5000

      - name: Metrics - Right
        uses: ahdinosaur/metrics@handle-more-repos
        with:
          filename: metrics.right.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_order: isocalendar, languages
          base: ""
          debug: yes
          repositories: 5000
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_ignored: html, css, vim script
          # plugin_languages_indepth: yes
          # plugin_languages_recent_load: 1000
          # plugin_languages_recent_days: 28
          # plugin_languages_sections: most-used, recently-used
          plugin_languages_skipped: ahdinosaur/prusa-mendel, ahdinosaur/dotfiles
          plugin_languages_threshold: 1%
